# Generated by Django 4.2.9 on 2026-08-17 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_game_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0008_hide_backfill_action_from_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_version', models.CharField(default='rocket_v1', max_length=32)),
                ('wager_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('auto_cashout_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('crash_point', models.DecimalField(decimal_places=2, max_digits=8)),
                ('started_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('cashed_out', 'Cashed Out'), ('crashed', 'Crashed')], default='active', max_length=16)),
                ('cashout_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('client_request_id', models.CharField(blank=True, max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rocket_round_credits', to='points.pointsledgerentry')),
                ('debit_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rocket_round_debits', to='points.pointsledgerentry')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rocket_rounds', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rocket_rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='rocket_rock_user_id_aab5b9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rocketround',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_rocket_round_per_user'),
        ),
        migrations.AddConstraint(
            model_name='rocketround',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('user', 'client_request_id'), name='unique_rocket_client_request_id'),
        ),
    ]
