# Generated by Django 4.2.9 on 2026-01-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link to external content', null=True),
        ),
    ]
