# Generated by Django 4.2.9 on 2026-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postlike_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cta_label',
            field=models.CharField(blank=True, default='', help_text='Button text for Call to Action', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='cta_link',
            field=models.URLField(blank=True, help_text='URL for Call to Action button', null=True),
        ),
    ]
