# Generated by Django 4.2.9 on 2026-08-12 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('points_value', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('max_awards_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PointsRedemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_amount', models.PositiveIntegerField()),
                ('reward_description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('staff_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_points_redemptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_redemption_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('earn', 'Earn'), ('redemption_hold', 'Redemption Hold'), ('redemption_refund', 'Redemption Refund'), ('redemption_finalize', 'Redemption Finalize'), ('adjustment', 'Adjustment')], max_length=24)),
                ('delta', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='points.pointaction')),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_awarded_entries', to=settings.AUTH_USER_MODEL)),
                ('redemption_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='points.pointsredemptionrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('lifetime_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pointsredemptionrequest',
            index=models.Index(fields=['status', 'created_at'], name='points_poin_status_6876e1_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsredemptionrequest',
            index=models.Index(fields=['user', 'status'], name='points_poin_user_id_5f0e4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointsredemptionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('user',), name='unique_active_points_redemption_per_user'),
        ),
        migrations.AddIndex(
            model_name='pointsledgerentry',
            index=models.Index(fields=['user', 'created_at'], name='points_poin_user_id_388ada_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsledgerentry',
            index=models.Index(fields=['entry_type', 'created_at'], name='points_poin_entry_t_f7be0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointsledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'action', 'idempotency_key'), name='unique_points_earn_idempotency_key'),
        ),
    ]
