# Generated by Django 4.2.9 on 2026-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('earn', 'Earn'), ('redemption_hold', 'Redemption Hold'), ('redemption_refund', 'Redemption Refund'), ('redemption_finalize', 'Redemption Finalize'), ('game_round', 'Game Round'), ('adjustment', 'Adjustment')], max_length=24),
        ),
    ]
