# Generated by Django 4.2.9 on 2026-08-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_alter_pointsledgerentry_entry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAdjustment',
            fields=[
            ],
            options={
                'verbose_name': 'Award / Deduct Points',
                'verbose_name_plural': 'Award / Deduct Points',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('points.pointsbalance',),
        ),
    ]
