# Generated by Django 4.2.9 on 2026-08-13 11:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_pointsadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='pointsledgerentry',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pointsledgerentry',
            name='delta',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
