# Generated by Django 4.2.9 on 2026-08-14 11:26

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0004_alter_pointsbalance_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsredemptionrequest',
            name='conversion_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pointsredemptionrequest',
            name='hi_rollin_credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PointsRedemptionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_redemption_points', models.PositiveIntegerField(default=5000)),
                ('rp_to_credit_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redemption Settings',
                'verbose_name_plural': 'Redemption Settings',
            },
        ),
    ]
