# Generated by Django 4.2.9 on 2026-08-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_seed_redemption_config_and_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointaction',
            name='is_visible_to_players',
            field=models.BooleanField(default=True),
        ),
    ]
