# Generated by Django 4.2.9 on 2026-01-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eligibilitycheckrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
    ]
