# Generated by Django 4.2.9 on 2026-01-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='base_prize_pool',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='prize_increment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
