# Generated by Django 4.2.9 on 2026-01-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_base_prize_pool_event_prize_increment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_prize_pool',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
