# Generated by Django 4.2.9 on 2026-09-03 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0008_hide_backfill_action_from_players'),
        ('games', '0002_game_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiLoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_version', models.CharField(default='hilo_v1', max_length=32)),
                ('wager_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_rank', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('J', 'J'), ('Q', 'Q'), ('K', 'K'), ('A', 'A')], max_length=2)),
                ('current_suit', models.CharField(choices=[('hearts', 'Hearts'), ('diamonds', 'Diamonds'), ('clubs', 'Clubs'), ('spades', 'Spades')], max_length=8)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('streak', models.PositiveSmallIntegerField(default=0)),
                ('steps_taken', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cashed_out', 'Cashed Out'), ('busted', 'Busted')], default='active', max_length=16)),
                ('capped', models.BooleanField(default=False)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('client_request_id', models.CharField(blank=True, max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilo_round_credits', to='points.pointsledgerentry')),
                ('debit_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilo_round_debits', to='points.pointsledgerentry')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hilo_rounds', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hilo_rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HiLoStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveSmallIntegerField()),
                ('from_rank', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('J', 'J'), ('Q', 'Q'), ('K', 'K'), ('A', 'A')], max_length=2)),
                ('from_suit', models.CharField(choices=[('hearts', 'Hearts'), ('diamonds', 'Diamonds'), ('clubs', 'Clubs'), ('spades', 'Spades')], max_length=8)),
                ('prediction', models.CharField(choices=[('higher', 'Higher'), ('lower', 'Lower')], max_length=6)),
                ('to_rank', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('J', 'J'), ('Q', 'Q'), ('K', 'K'), ('A', 'A')], max_length=2)),
                ('to_suit', models.CharField(choices=[('hearts', 'Hearts'), ('diamonds', 'Diamonds'), ('clubs', 'Clubs'), ('spades', 'Spades')], max_length=8)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('push', 'Push'), ('loss', 'Loss')], max_length=4)),
                ('step_multiplier', models.DecimalField(decimal_places=2, max_digits=8)),
                ('multiplier_after', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='hilo.hiloround')),
            ],
            options={
                'ordering': ['round_id', 'step_index'],
                'unique_together': {('round', 'step_index')},
            },
        ),
        migrations.AddIndex(
            model_name='hiloround',
            index=models.Index(fields=['user', 'created_at'], name='hilo_hiloro_user_id_65866e_idx'),
        ),
        migrations.AddConstraint(
            model_name='hiloround',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_hilo_round_per_user'),
        ),
        migrations.AddConstraint(
            model_name='hiloround',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('user', 'client_request_id'), name='unique_hilo_client_request_id'),
        ),
    ]
