# Generated by Django 4.2.9 on 2026-08-14 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0008_hide_backfill_action_from_players'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_version', models.CharField(default='slot_v1', max_length=32)),
                ('wager_amount', models.PositiveIntegerField()),
                ('reel_1_stop', models.PositiveSmallIntegerField()),
                ('reel_2_stop', models.PositiveSmallIntegerField()),
                ('reel_3_stop', models.PositiveSmallIntegerField()),
                ('grid_snapshot', models.JSONField()),
                ('winning_lines', models.JSONField(default=list)),
                ('total_multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_result', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client_request_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slot_rounds', to='games.game')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_round', to='points.pointsledgerentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='slots_slotr_user_id_c8fe93_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='slotround',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('user', 'client_request_id'), name='unique_slot_client_request_id'),
        ),
    ]
