# Generated by Django 4.2.9 on 2026-06-23 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(blank=True, default='', max_length=80)),
                ('session_id', models.CharField(blank=True, default='', max_length=80)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('register', 'Register'), ('login', 'Login'), ('logout', 'Logout'), ('redemption', 'Redemption'), ('event_registration', 'Event Registration'), ('custom', 'Custom')], db_index=True, max_length=40)),
                ('event_name', models.CharField(blank=True, default='', max_length=120)),
                ('user_type', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('full_path', models.CharField(blank=True, default='', max_length=500)),
                ('method', models.CharField(blank=True, default='', max_length=12)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('medium', models.CharField(blank=True, default='', max_length=120)),
                ('campaign', models.CharField(blank=True, default='', max_length=160)),
                ('device_type', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('browser', models.CharField(blank=True, default='', max_length=80)),
                ('os', models.CharField(blank=True, default='', max_length=80)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('region', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='analytics_a_event_t_002468_idx'), models.Index(fields=['user_type', '-created_at'], name='analytics_a_user_ty_091a43_idx'), models.Index(fields=['path', '-created_at'], name='analytics_a_path_02fe46_idx'), models.Index(fields=['source', '-created_at'], name='analytics_a_source_d6a159_idx')],
            },
        ),
    ]
