# Generated by Django 4.2.9 on 2026-01-22 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_room_options_room_client_alter_room_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('staff', models.OneToOneField(blank=True, limit_choices_to={'user_type': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_support_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
