# Generated by Django 4.2.9 on 2026-01-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_supportroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportroom',
            name='room_type',
            field=models.CharField(choices=[('player', 'Player Support'), ('agent', 'Agent Support'), ('all', 'General Support')], default='all', max_length=10),
        ),
    ]
