# Generated by Django 4.2.9 on 2026-01-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_supportroom_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/'),
        ),
    ]
