# Generated by Django 4.2.9 on 2026-01-23 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_alter_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='client',
            field=models.OneToOneField(blank=True, limit_choices_to={'user_type__in': ['player', 'agent']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
