# Generated by Django 4.2.9 on 2026-01-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_room_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='staff_assigned',
            new_name='current_handler',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
    ]
