# Generated by Django 4.2.9 on 2026-01-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_staff_assigned_room_current_handler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_chats', to='chat.supportroom'),
        ),
    ]
