# Generated by Django 4.2.9 on 2026-01-26 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0010_message_edited_at_message_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportroom',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_support_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
