# Generated by Django 4.2.9 on 2026-01-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_supportroom_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportroom',
            name='room_type',
            field=models.CharField(choices=[('player', 'Player Support'), ('agent', 'Agent Support'), ('event', 'Event Support'), ('all', 'General Support')], default='all', max_length=10),
        ),
    ]
