# Generated by Django 4.2.9 on 2026-06-05 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0018_room_direct_request_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='direct_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_player_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
