# Generated by Django 4.2.9 on 2026-01-27 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_user_id',
            field=models.CharField(blank=True, help_text='External user ID from another service for verification', max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ExternalUserID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='External user ID that users can verify against', max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this user ID has been used for verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for admin reference')),
                ('used_by', models.ForeignKey(blank=True, help_text='User who used this ID for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_external_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External User ID',
                'verbose_name_plural': 'External User IDs',
                'ordering': ['-created_at'],
            },
        ),
    ]
