# Generated by Django 4.2.9 on 2026-01-28 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('accounts', '0005_verificationrequest_delete_externaluserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event related to this verification request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='events.event'),
        ),
    ]
