# Generated by Django 4.2.9 on 2026-02-03 15:28

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_verificationrequest_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSearch',
            fields=[
            ],
            options={
                'verbose_name': 'Player Search',
                'verbose_name_plural': 'Player Search',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
