# Generated by Django 4.2.9 on 2026-02-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_playersearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. Must be unique.', max_length=254, unique=True),
        ),
    ]
