# Generated by Django 4.2.9 on 2026-02-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.CharField(help_text="The version string matching pubspec.yaml (e.g., '1.0.0+1')", max_length=20)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether users are forced to update to this version')),
                ('release_notes', models.TextField(blank=True, help_text='Information about what is new in this release')),
                ('apk_file', models.FileField(blank=True, help_text='The actual Android .apk file for download', null=True, upload_to='app_releases/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='If multiple versions exist, only the one marked is_active is served to clients.')),
            ],
            options={
                'verbose_name': 'App Release Version',
                'verbose_name_plural': 'App Release Versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
