# Generated by Django 4.2.9 on 2026-08-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp', '0002_seed_xp_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpbalance',
            name='pending_celebration_rank',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
