# Generated by Django 4.2.9 on 2026-09-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp', '0005_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpaction',
            name='action_url',
            field=models.CharField(blank=True, help_text='Where the tile links to, e.g. "/games/hilo". Leave blank for something the player cannot act on directly (like Daily Login) and the tile renders without a link.', max_length=200),
        ),
        migrations.AddField(
            model_name='xpaction',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=100, help_text='Lower numbers appear first in both lists. Ties fall back to slug order.'),
        ),
        migrations.AddField(
            model_name='xpaction',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional emoji shown on the tile, e.g. 🃏. Falls back to a suit glyph.', max_length=8),
        ),
        migrations.AddField(
            model_name='xpaction',
            name='is_achievement',
            field=models.BooleanField(default=False, help_text='Show this as an achievement badge on player profiles.'),
        ),
        migrations.AddField(
            model_name='xpaction',
            name='is_daily_checklist',
            field=models.BooleanField(default=False, help_text="Show this on the player's Daily Challenges checklist (the /challenges page, the home banner and the rewards page). Leave off for background actions players never see as a task, like qualified_gameplay."),
        ),
        migrations.AlterField(
            model_name='xpaction',
            name='challenge_source_action',
            field=models.ForeignKey(blank=True, help_text='The action being counted, e.g. "gameplay_round" for "play N rounds".', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='challenge_dependents', to='xp.xpaction'),
        ),
        migrations.AlterField(
            model_name='xpaction',
            name='challenge_target_count',
            field=models.PositiveIntegerField(blank=True, help_text='How many of the source action are needed today. Set with Challenge source action.', null=True),
        ),
    ]
