# Generated by Django 4.2.9 on 2026-09-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp', '0007_flag_existing_challenges_and_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpaction',
            name='challenge_period',
            field=models.CharField(choices=[('daily', 'Daily - resets at midnight'), ('weekly', 'Weekly - resets Monday'), ('event', 'Event - runs once, between the two dates below')], default='daily', help_text='How often the challenge target resets. "Event" needs the two dates below; the other two ignore them.', max_length=8),
        ),
        migrations.AddField(
            model_name='xpaction',
            name='event_ends_at',
            field=models.DateTimeField(blank=True, help_text='Event period only - the challenge is invisible and cannot be earned after this.', null=True),
        ),
        migrations.AddField(
            model_name='xpaction',
            name='event_starts_at',
            field=models.DateTimeField(blank=True, help_text='Event period only - the challenge is invisible and cannot be earned before this.', null=True),
        ),
    ]
