# Generated by Django 4.2.9 on 2026-09-03 14:42
# Hand-split from the auto-generated migration (which combined this with
# removing the old FK) so a data migration can copy challenge_source_action
# -> challenge_source_actions in between, before the old column is dropped.
# See 0010 (data copy) and 0011 (drops the old FK).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp', '0008_xpaction_challenge_period_xpaction_event_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpaction',
            name='challenge_source_actions',
            field=models.ManyToManyField(blank=True, help_text='The action(s) being counted, e.g. pick "Plinko Rounds" alone to scope this challenge to just Plinko, several per-game counters to cover several games, or "Gameplay Round" alone to count every game.', related_name='challenge_dependents', to='xp.xpaction'),
        ),
        migrations.AlterField(
            model_name='xpaction',
            name='challenge_target_count',
            field=models.PositiveIntegerField(blank=True, help_text='How many of the source action(s) are needed. Set with Challenge source action(s).', null=True),
        ),
    ]
