# Generated by Django 4.2.9 on 2026-09-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp', '0011_remove_challenge_source_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpaction',
            name='rotation_pool',
            field=models.BooleanField(default=False, help_text='Daily challenges only. When on, this challenge is only live on some days (a random subset of the whole rotation pool, sized by Daily Rotation Settings) rather than every day - build a larger pool of these than the daily count and a different subset shows each day.'),
        ),
    ]
