# Generated by Django 4.2.9 on 2026-09-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp', '0012_xpaction_rotation_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpaction',
            name='rotation_pool',
            field=models.BooleanField(default=False, help_text="Daily or Weekly challenges only. When on, this challenge is only live during some periods (a random subset of its period's whole rotation pool, sized by Rotation Settings) rather than every period - build a larger pool of these than the configured count and a different subset shows each day (Daily) or each week (Weekly)."),
        ),
    ]
