# Generated by Django 4.2.9 on 2026-08-12 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0002_alter_pointsledgerentry_entry_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlinkoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveSmallIntegerField(choices=[(8, '8'), (12, '12'), (16, '16')])),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8)),
                ('wager_amount', models.PositiveIntegerField()),
                ('slot_index', models.PositiveSmallIntegerField()),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payout_amount', models.PositiveIntegerField()),
                ('path', models.JSONField()),
                ('balance_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plinko_rounds', to='games.game')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plinko_round', to='points.pointsledgerentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plinko_rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='plinko_plin_user_id_6a91e6_idx')],
            },
        ),
    ]
