# Generated by Django 4.2.9 on 2026-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinko', '0002_seed_plinko_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='plinkoround',
            name='drop_offset',
            field=models.FloatField(default=0.0),
        ),
    ]
