# Generated by Django 4.2.9 on 2026-08-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinko', '0003_plinkoround_drop_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plinkoround',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='plinkoround',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='plinkoround',
            name='rows',
            field=models.PositiveSmallIntegerField(choices=[(8, '8')]),
        ),
    ]
