# Generated by Django 4.2.9 on 2026-08-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinko', '0004_alter_plinkoround_balance_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plinkoround',
            name='drop_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plinkoround',
            name='mode',
            field=models.CharField(choices=[('classic', 'Classic'), ('free_drop', 'Free Drop')], default='classic', max_length=16),
        ),
    ]
