# Generated by Django 4.2.9 on 2026-08-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinko', '0005_plinkoround_drop_position_plinkoround_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='plinkoround',
            name='physics_seed',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
