# Generated by Django 4.2.9 on 2026-09-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xp', '0011_remove_challenge_source_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
            ],
            options={
                'verbose_name': 'Daily Challenge',
                'verbose_name_plural': 'Daily Challenges',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('xp.xpaction',),
        ),
        migrations.CreateModel(
            name='SpecialChallenge',
            fields=[
            ],
            options={
                'verbose_name': 'Special Challenge',
                'verbose_name_plural': 'Special Challenges',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('xp.xpaction',),
        ),
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
            ],
            options={
                'verbose_name': 'Weekly Challenge',
                'verbose_name_plural': 'Weekly Challenges',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('xp.xpaction',),
        ),
    ]
