# Generated by Django 4.2.9 on 2026-09-03 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRotationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_count', models.PositiveSmallIntegerField(default=3, help_text='How many rotation-pool Daily Challenges are live each day. 0 hides the whole pool. A count at or above the pool size shows the entire pool every day (no rotation effect).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Rotation Settings',
                'verbose_name_plural': 'Daily Rotation Settings',
            },
        ),
    ]
