# Generated by Django 4.2.9 on 2026-08-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpresence',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
